### ISSUE TITLE
What license does segmentspy use?

### ISSUE THREAD

**Issue by quodt** [polyfractal/elasticsearch-segmentspy#1]
i would like to integrate segmentspy in my project and so i was wondering what kind of license segmentspy uses?

**Comment by polyfractal** [comment]
Whoops, sorry about that.  Just [added an MIT license](https://github.com/polyfractal/elasticsearch-segmentspy/blob/master/LICENSE) to the repo.  Integrate away!

Out of curiosity, what project are you working on?

**Comment by quodt** [comment]
hi, thanks for adding the license.
we like to distribute this plugin (and some more) together with elasticsearch as a bundle package.

**Comment by polyfractal** [comment]
Nifty.  Keep me updated, would love to see the finished package! :)
