### ISSUE TITLE
Forces https

### ISSUE THREAD

**Issue by mpcarl** [polyfractal/elasticsearch-segmentspy#4]
Our ES server is running on HTTPS and not HTTP.  SegmentSpy seems to be forcing the connection to http instead of accessing the data using the same protocol as the browser used to load the page.

**Comment by dentarg** [comment]
I think this issue can be closed as #5 was merged.

**Comment by polyfractal** [comment]
Whoops, you're right.  Forgot to close this after the PR.  Closing!
